################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ French language ##################
[kr]
languageName = "Korean"
languageCode = "ko-KR"
contentDir = "content/korean"
weight = 2
